-- V3: Add time limit, practice mode
ALTER TABLE exams ADD COLUMN IF NOT EXISTS duration_minutes INTEGER DEFAULT 20;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS mode VARCHAR(10) DEFAULT 'EXAM';
